services:
  - type: web
    name: qinterview-ai-backend
    env: node
    plan: free
    region: oregon
    rootDirectory: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_GENAI_API_KEY
        sync: false
